import './globals.css'
import type { Metadata } from 'next'

import { ThemeProvider } from '@/components/theme-provider'
import { caveat, poppins } from '@/lib/localFonts'
import Header from '@/components/header'
import ReturnToHeader from '@/components/return-to-header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${poppins.variable} ${caveat.variable}`}>
        <ThemeProvider enableSystem attribute="class" defaultTheme="light">
          <Header />
          {children}
          <ReturnToHeader />
        </ThemeProvider>
      </body>
    </html>
  )
}
